spring:
  application:
    name : config-server
  profiles.active: dev
  cloud:
    config:
      server:
        git:uri: https://github.com/ThoreauZZ/spring-cloud-example.git
#           uri: file:/github/spring-learn
        searchPaths: config-repo


---
spring:
  profiles: dev

server:
  port : 9000

  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtualHost: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:9001/eureka/


---
spring:
  profiles: docker

server:
  port : ${SERVICE_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}

