version: '2'
services:
  mysql:
    image: erdaoya/cloud-data-mysql
    ports:
     - "3306:3306"

  config:
    image: erdaoya/cloud-config-service
    ports:
     - "9000:9000"

  eureka:
    image: erdaoya/cloud-eureka-service
    ports:
     - "9001:9001"
    links:
     - config

  user:
    image: erdaoya/cloud-user-service
    ports:
     - "9002:9002"
    links:
     - config:config
     - eureka:discovery
     - mysql:db
    command: ["./wait-for-it.sh", "config:9000", "--","java","-jar","/cloud-user-service.jar"]

  client:
    image: erdaoya/cloud-service-client
    ports:
      - "9005:9005"
    links:
      - config:config
      - eureka:discovery
      - user:user

  gateway:
    image: erdaoya/cloud-api-gateway
    ports:
     - "9006:9006"
    links:
     - config:config
     - eureka:discovery
     - mysql:db
     - user:user
  turbine:
    image: erdaoya/cloud-turbine-dashbord
    ports:
     - "9010:9010"
    links:
     - client:client
     - user:user
     - eureka:discovery
