version: '2'
services:
  mysql:
    image: erdaoya/cloud-data-mysql
    ports:
     - "3306:3306"

  rabbitmq:
      image: rabbitmq:management
      ports:
       - "5672:5672"
       - "15672:15672"

  config:
    image: erdaoya/cloud-config-service
    ports:
     - "9000:9000"

  eureka:
    image: erdaoya/cloud-eureka-service
    ports:
     - "9001:9001"
    links:
     - config
  zipkin:
    image: erdaoya/cloud-zipkin-ui
    ports:
      - "9012:9012"
    links:
      - eureka:discovery
      - rabbitmq:rabbitmq
  user:
    image: erdaoya/cloud-user-service
    ports:
     - "9002:9002"
    links:
     - config:config
     - eureka:discovery
     - mysql:db
     - zipkin:zipkin
     - rabbitmq:rabbitmq
    command: ["./wait-for-it.sh", "config:9000", "--","java","-jar","/cloud-user-service.jar"]

  client:
    image: erdaoya/cloud-service-client
    ports:
      - "9005:9005"
    links:
      - config:config
      - eureka:discovery
      - user:user
      - zipkin:zipkin
      - rabbitmq:rabbitmq

  gateway:
    image: erdaoya/cloud-api-gateway
    ports:
     - "9006:9006"
    links:
     - config:config
     - eureka:discovery
     - mysql:db
     - user:user
     - client:client
     - zipkin:zipkin
     - rabbitmq:rabbitmq

  turbine:
    image: erdaoya/cloud-turbine-dashbord
    ports:
     - "9010:9010"
    links:
     - client:client
     - user:user
     - eureka:discovery
