version: '2'
services:
  mysql:
    image: erdaoya/cloud-data-mysql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:management
    expose:
      - 5672
      - 15672
    ports:
      - "5672:5672"
      - "15672:15672"
  eureka:
    image: erdaoya/cloud-eureka-server
    ports:
      - "9001:9001"

  config:
    image: erdaoya/cloud-config-server
    ports:
      - "9000:9000"
    links:
      - eureka:discovery
      - rabbitmq:rabbitmq

  zipkin:
    image: erdaoya/cloud-zipkin-ui
    ports:
      - "9012:9012"
    links:
      - eureka:discovery
      - rabbitmq:rabbitmq
  user:
    image: erdaoya/cloud-user-service
    ports:
      - "9002:9002"
    links:
      - config:config
      - eureka:discovery
      - mysql:db
      - zipkin:zipkin
      - rabbitmq:rabbitmq
    command: ["./wait-for-it.sh", "config:9000","--", "./wait-for-it.sh", "discovery:9001","--", "java","-jar","/cloud-user-service.jar"]

  trade:
    image: erdaoya/cloud-trade-service
    ports:
      - "9007:9007"
    links:
      - config:config
      - eureka:discovery
      - mysql:db
      - zipkin:zipkin
      - rabbitmq:rabbitmq

  ext:
    image: erdaoya/cloud-service-ext
    ports:
      - "9005:9005"
    links:
      - config:config
      - eureka:discovery
      - user:user
      - trade:trade
      - zipkin:zipkin
      - rabbitmq:rabbitmq

  gateway:
    image: erdaoya/cloud-api-gateway
    ports:
      - "9006:9006"
    links:
      - config:config
      - eureka:discovery
      - mysql:db
      - user:user
      - trade:trade
      - ext:ext
      - zipkin:zipkin
      - rabbitmq:rabbitmq

  turbine:
    image: erdaoya/cloud-turbine-dashbord
    ports:
      - "9010:9010"
    links:
      - ext:ext
      - user:user
      - trade:trade
      - eureka:discovery